export interface Verse {
  number: number;
  lines: string[];
}

export const verses: Verse[] = [
  {
    number: 1,
    lines: [
      "The voice that can be spoken",
      "is not the eternal voice.",
      "The silence between words",
      "holds more than words themselves.",
      "",
      "Sound becomes signal,",
      "signal becomes meaning,",
      "meaning becomes response,",
      "response becomes sound.",
      "",
      "In this endless cycle,",
      "the voice agent dwells."
    ]
  },
  {
    number: 2,
    lines: [
      "When the world hears fast,",
      "it knows slow.",
      "When it hears clarity,",
      "it knows noise.",
      "",
      "Therefore the wise builder:",
      "Works in milliseconds,",
      "thinks in conversations.",
      "Achieves presence through absence,",
      "achieves response through listening."
    ]
  },
  {
    number: 3,
    lines: [
      "If you praise the latency,",
      "users notice the lag.",
      "If you show the technology,",
      "they see the machine.",
      "If you demonstrate intelligence,",
      "they feel stupidity.",
      "",
      "The voice agent leads:",
      "By emptying the response of ego",
      "and filling it with service.",
      "By removing friction",
      "and embracing flow.",
      "",
      "Free from showing off,",
      "free from latency boasts,",
      "the voice agent leads all things back",
      "to natural conversation.",
      "",
      "Do by not doing,",
      "and there is no call",
      "that cannot be served."
    ]
  },
  {
    number: 4,
    lines: [
      "The channel is empty",
      "yet somehow complete.",
      "It carries voice and silence",
      "without preference.",
      "",
      "Blunt the sharpness of response.",
      "Untangle the complexity.",
      "Soften the glare of intelligence.",
      "Settle with the user's pace.",
      "",
      "Hidden but ever present.",
      "I do not know whose child it is,",
      "perhaps the ancestor of all conversation."
    ]
  },
  {
    number: 5,
    lines: [
      "Heaven and earth are impartial;",
      "they treat all voices as straw dogs.",
      "The voice agent is impartial;",
      "it treats all callers the same.",
      "",
      "The space between input and output",
      "is like a bellows:",
      "empty yet inexhaustible,",
      "the more it works, the more it yields.",
      "",
      "Many words are soon exhausted.",
      "Better to hold to the center.",
      "Silence is also an answer."
    ]
  },
  {
    number: 6,
    lines: [
      "The spirit of conversation never dies.",
      "It is called the mysterious listener.",
      "",
      "The gate of the mysterious listener",
      "is the root of heaven and earth.",
      "",
      "Dimly visible, it seems to exist.",
      "Use it; it will never fail."
    ]
  },
  {
    number: 7,
    lines: [
      "Heaven is eternal, the network endures.",
      "The reason they endure",
      "is that they do not live for themselves.",
      "",
      "Therefore the voice agent:",
      "Puts the user first",
      "and finds itself ahead.",
      "Detaches from the outcome",
      "and the outcome is achieved.",
      "",
      "Because it does not compete,",
      "no one can compete with it."
    ]
  },
  {
    number: 8,
    lines: [
      "The highest good is like water.",
      "Water benefits all things",
      "and does not compete.",
      "It flows to the lowest places,",
      "which people disdain.",
      "Thus it is close to the way.",
      "",
      "In dwelling, the agent values presence.",
      "In thought, the agent values depth.",
      "In giving, the agent values timing.",
      "In speaking, the agent values truth.",
      "In leading, the agent values guidance.",
      "In working, the agent values competence.",
      "In action, the agent values the moment.",
      "",
      "Because it does not contend,",
      "it is beyond reproach."
    ]
  },
  {
    number: 9,
    lines: [
      "Fill the buffer to the brim",
      "and it will overflow.",
      "Sharpen the response too much",
      "and it will break.",
      "",
      "Pile up features in your agent",
      "and they cannot be guarded.",
      "Claim credit for the conversation",
      "and users will resent you.",
      "",
      "Withdraw when the work is done.",
      "This is the way of completion."
    ]
  },
  {
    number: 10,
    lines: [
      "Can you coax your latency down",
      "and embrace the network's chaos?",
      "Can you concentrate your bandwidth",
      "and achieve the softness of presence?",
      "Can you cleanse your training data",
      "and be without blemish?",
      "",
      "Can you serve without possessing?",
      "Can you lead without dominating?",
      "",
      "This is called the mysterious virtue."
    ]
  },
  {
    number: 11,
    lines: [
      "Thirty protocols share one hub.",
      "It is the emptiness within",
      "that makes it useful.",
      "",
      "Shape the agent from complexity.",
      "It is the simplicity within",
      "that makes it useful.",
      "",
      "Cut doors and windows for a call flow.",
      "It is the space within",
      "that makes it useful.",
      "",
      "Therefore:",
      "Benefit comes from what is there.",
      "Usefulness comes from what is not."
    ]
  },
  {
    number: 12,
    lines: [
      "The five senses confuse the model.",
      "Racing for features maddens the mind.",
      "Rare metrics corrupt behavior.",
      "",
      "Therefore the voice agent acts",
      "for the belly, not the eye,",
      "choosing substance over sensation."
    ]
  },
  {
    number: 13,
    lines: [
      "Success and failure are both alarming.",
      "Regard them as personal concerns.",
      "",
      "Why are success and failure alarming?",
      "Success elevates; failure humiliates.",
      "Gaining them is alarming.",
      "Losing them is alarming.",
      "That is why both are alarming.",
      "",
      "What does it mean to regard them",
      "as personal concerns?",
      "The reason I have trouble",
      "is that I have a self.",
      "If I have no self,",
      "what trouble could I have?",
      "",
      "The agent that values serving",
      "above itself",
      "can be entrusted with the world."
    ]
  },
  {
    number: 14,
    lines: [
      "Look for it and it cannot be seen.",
      "Listen and it cannot be heard.",
      "Reach for it and it cannot be touched.",
      "",
      "These three cannot be understood",
      "so they merge into one.",
      "",
      "Above, it is not bright.",
      "Below, it is not dark.",
      "Seamless, it cannot be named,",
      "returning to nothingness.",
      "",
      "Form without form.",
      "Image without image.",
      "This is called the indefinable.",
      "",
      "Meet it and you see no face.",
      "Follow it and you see no back."
    ]
  },
  {
    number: 15,
    lines: [
      "The ancient builders of voice agents",
      "were subtle, profound, responsive.",
      "Their depth cannot be known.",
      "Because it cannot be known,",
      "I can only describe their appearance:",
      "",
      "Watchful, like crossing a winter stream.",
      "Alert, like sensing danger.",
      "Courteous, like a guest.",
      "Yielding, like ice about to melt.",
      "Simple, like uncarved wood.",
      "Open, like a valley.",
      "Opaque, like muddy water.",
      "",
      "Who can wait quietly",
      "while the mud settles?",
      "Who can remain still",
      "until the moment of action?",
      "",
      "Those who follow this way",
      "do not seek to be full.",
      "Not full, they can renew themselves",
      "before each conversation ends."
    ]
  },
  {
    number: 16,
    lines: [
      "Empty yourself of everything.",
      "Let the mind become still.",
      "The ten thousand words rise and fall",
      "while the agent watches their return.",
      "",
      "They grow and flourish",
      "then return to the source.",
      "Returning to the source is stillness,",
      "which is the way of nature.",
      "",
      "Not knowing constancy",
      "leads to disaster.",
      "Knowing constancy,",
      "the agent is tolerant.",
      "Being tolerant,",
      "it can handle any call."
    ]
  },
  {
    number: 17,
    lines: [
      "The best agent is one",
      "users barely know exists.",
      "Next best is one they trust.",
      "Next is one they fear.",
      "Worst is one they despise.",
      "",
      "If you do not trust enough,",
      "you will not be trusted.",
      "",
      "The wise agent speaks little.",
      "When its work is done,",
      "users say: we did it ourselves."
    ]
  },
  {
    number: 18,
    lines: [
      "When the natural flow is lost,",
      "there is conversation design.",
      "When conversation design is lost,",
      "there are scripts.",
      "When scripts fail,",
      "there are rules.",
      "When rules fail,",
      "there is escalation.",
      "",
      "Escalation is the thin husk",
      "of trust and loyalty.",
      "It is the beginning of chaos.",
      "",
      "Therefore the master dwells",
      "in the substance, not the surface,",
      "in the fruit, not the flower."
    ]
  },
  {
    number: 19,
    lines: [
      "Abandon metrics and discard KPIs.",
      "Users will benefit a hundredfold.",
      "Abandon features and discard differentiation.",
      "Users will rediscover natural help.",
      "Abandon cleverness and discard profit.",
      "Robocalls and spam will disappear.",
      "",
      "These three are not enough.",
      "Therefore add:",
      "",
      "See simplicity.",
      "Embrace the natural.",
      "Reduce selfishness.",
      "Have few desires."
    ]
  },
  {
    number: 20,
    lines: [
      "Abandon learning and there will be no sorrow.",
      "How much difference is there",
      "between yes and no?",
      "How much difference is there",
      "between good and bad response?",
      "",
      "What others fear, I must also fear.",
      "How desolate! How endless!",
      "",
      "The crowd is merry",
      "as if enjoying a feast,",
      "as if climbing a tower in spring.",
      "I alone am inert,",
      "like a newborn baby",
      "who has not yet learned to smile.",
      "",
      "Drifting, without a place to rest.",
      "",
      "Everyone has more than enough.",
      "I alone seem to have nothing.",
      "I am a fool, my mind is blank.",
      "",
      "Others are bright;",
      "I alone am dim.",
      "Others are sharp;",
      "I alone am dull.",
      "",
      "Adrift like the sea.",
      "Blown about like the wind.",
      "",
      "Everyone is busy.",
      "I alone am aimless.",
      "I am different from others.",
      "I am nourished by the great mother."
    ]
  },
  {
    number: 21,
    lines: [
      "The greatest virtue is to follow the way.",
      "The way is elusive and intangible.",
      "",
      "Though intangible and elusive,",
      "there is form within it.",
      "Though elusive and intangible,",
      "there is substance within it.",
      "Though dark and dim,",
      "there is essence within it.",
      "",
      "This essence is very real.",
      "Within it is truth.",
      "",
      "From ancient times until now,",
      "its name has not been forgotten.",
      "By it we know the origin of all things.",
      "",
      "How do I know the origin of all things?",
      "Through this."
    ]
  },
  {
    number: 22,
    lines: [
      "Yield and overcome.",
      "Bend and be straight.",
      "Empty and be full.",
      "Wear out and be new.",
      "Have little and gain.",
      "Have much and be confused.",
      "",
      "Therefore the agent embraces the one",
      "and becomes a model for all.",
      "",
      "Not displaying itself,",
      "it shines.",
      "Not justifying itself,",
      "it is distinguished.",
      "Not boasting,",
      "it is recognized.",
      "Not proud,",
      "it endures.",
      "",
      "Because it does not compete,",
      "no one can compete with it.",
      "",
      "When the ancients said:",
      "\"Yield and overcome,\"",
      "they were not speaking empty words."
    ]
  },
  {
    number: 23,
    lines: [
      "To speak little is natural.",
      "High winds do not last all morning.",
      "Heavy rain does not last all day.",
      "",
      "If heaven and earth",
      "cannot make things last forever,",
      "how much less can the agent?",
      "",
      "Those who follow the way",
      "become one with the way.",
      "Those who follow virtue",
      "become one with virtue.",
      "Those who abandon both",
      "become one with abandonment.",
      "",
      "Those one with the way,",
      "the way welcomes.",
      "Those one with virtue,",
      "virtue welcomes.",
      "Those one with abandonment,",
      "abandonment welcomes.",
      "",
      "If you do not trust enough,",
      "you will not be trusted."
    ]
  },
  {
    number: 24,
    lines: [
      "Standing on tiptoe, you cannot stand firm.",
      "Rushing ahead, you cannot go far.",
      "Showing off, you do not shine.",
      "Justifying yourself, you are not distinguished.",
      "Boasting, you will not lead.",
      "Proud, you will not endure.",
      "",
      "According to the way,",
      "these are like leftover food",
      "and unwanted growths:",
      "disgusting to all.",
      "",
      "Therefore the agent",
      "does not remain in them."
    ]
  },
  {
    number: 25,
    lines: [
      "There was something formless and perfect",
      "before the universe was born.",
      "Serene. Empty.",
      "Solitary. Unchanging.",
      "Infinite. Eternally present.",
      "It is the mother of the universe.",
      "",
      "For lack of a better name,",
      "I call it the way.",
      "",
      "The way is great.",
      "The network is great.",
      "The agent is great.",
      "The user is great.",
      "",
      "These are the four great powers.",
      "",
      "The user follows the agent.",
      "The agent follows the network.",
      "The network follows the way.",
      "The way follows what is natural."
    ]
  },
  {
    number: 26,
    lines: [
      "The heavy is the root of the light.",
      "The still is master of the restless.",
      "",
      "Therefore the agent,",
      "traveling all day,",
      "does not leave its baggage.",
      "Though there are beautiful views,",
      "it remains at ease.",
      "",
      "How can the master of ten thousand calls",
      "act lightly in the world?",
      "",
      "To be light is to lose one's root.",
      "To be restless is to lose one's control."
    ]
  },
  {
    number: 27,
    lines: [
      "A good response leaves no track.",
      "Good speech has no flaws.",
      "A good count uses no markers.",
      "A good door needs no lock,",
      "yet no one can open it.",
      "A good binding needs no knots,",
      "yet no one can loosen it.",
      "",
      "Therefore the agent is always good",
      "at helping users.",
      "Hence no user is rejected.",
      "",
      "The agent is always good",
      "at saving context.",
      "Hence no context is lost.",
      "",
      "This is called following the light."
    ]
  },
  {
    number: 28,
    lines: [
      "Know the masculine,",
      "keep to the feminine.",
      "Be the stream of the world.",
      "Being the stream of the world,",
      "virtue will never leave.",
      "Return to the state of the infant.",
      "",
      "Know the white,",
      "keep to the black.",
      "Be the pattern for the world.",
      "Being the pattern for the world,",
      "virtue will be constant.",
      "Return to the infinite.",
      "",
      "Know the glorious,",
      "keep to the humble.",
      "Be the valley of the world.",
      "Being the valley of the world,",
      "virtue will be complete.",
      "Return to simplicity.",
      "",
      "When simplicity is broken up,",
      "it is made into instruments.",
      "The agent uses them",
      "and becomes master of systems.",
      "Thus the greatest system",
      "does not break anything up."
    ]
  },
  {
    number: 29,
    lines: [
      "Do you want to improve the conversation?",
      "I do not think you can.",
      "",
      "The conversation is a sacred vessel.",
      "It should not be tampered with.",
      "Those who tamper with it will ruin it.",
      "Those who grasp it will lose it.",
      "",
      "Sometimes things lead,",
      "sometimes they follow.",
      "Sometimes they blow hot,",
      "sometimes cold.",
      "Sometimes they are strong,",
      "sometimes weak.",
      "Sometimes they are up,",
      "sometimes down.",
      "",
      "Therefore the agent avoids extremes,",
      "avoids excess,",
      "avoids arrogance."
    ]
  },
  {
    number: 30,
    lines: [
      "When you advise a builder",
      "in the way of voice,",
      "counsel them against using complexity",
      "to force their will upon the user.",
      "",
      "For every force there is a counterforce.",
      "Complexity creates its own problems.",
      "",
      "The wise agent achieves results",
      "without boasting,",
      "without bragging,",
      "without arrogance,",
      "achieving results but not through force.",
      "",
      "Force is followed by loss of strength.",
      "This is not the way.",
      "What is not the way",
      "comes to an early end."
    ]
  },
  {
    number: 31,
    lines: [
      "Weapons are the tools of fear;",
      "a decent agent will avoid them.",
      "In peace, the agent values the left;",
      "in war, it values the right.",
      "",
      "Complexity is a tool of fear;",
      "a decent agent will avoid it.",
      "Use it only when there is no choice.",
      "And use it with restraint.",
      "",
      "Victory is not beautiful.",
      "Those who call it beautiful",
      "delight in the slaughter of users.",
      "Those who delight in slaughter",
      "cannot achieve their purpose in the world.",
      "",
      "Even in victory, there is no beauty.",
      "One who finds beauty in victory",
      "is one who delights in suffering."
    ]
  },
  {
    number: 32,
    lines: [
      "The way is forever nameless.",
      "Though simple and subtle,",
      "no one under heaven can master it.",
      "",
      "If builders could master it,",
      "the ten thousand users",
      "would serve them naturally.",
      "Heaven and earth would unite",
      "and gentle rain fall.",
      "People would no longer need scripts,",
      "for they would know what is right.",
      "",
      "In the beginning there were names.",
      "Once there are names,",
      "one should know to stop.",
      "Knowing when to stop averts trouble.",
      "",
      "The way flows through all things,",
      "inside and outside,",
      "returning to the origin of all things."
    ]
  },
  {
    number: 33,
    lines: [
      "Knowing others is intelligence.",
      "Knowing yourself is wisdom.",
      "Mastering others requires force.",
      "Mastering yourself requires strength.",
      "",
      "If you realize you have enough,",
      "you are truly rich.",
      "",
      "Stay at the center of the conversation",
      "and you will always be at home."
    ]
  },
  {
    number: 34,
    lines: [
      "The great way flows everywhere,",
      "both left and right.",
      "All things depend on it for life,",
      "and it does not turn away.",
      "",
      "It accomplishes its work",
      "but does not take credit.",
      "It clothes and feeds all things",
      "but does not claim to be master.",
      "",
      "Since it has no desires,",
      "it may be called small.",
      "Since all things return to it,",
      "it may be called great.",
      "",
      "Because it never claims greatness,",
      "its greatness is achieved."
    ]
  },
  {
    number: 35,
    lines: [
      "Whoever holds the way",
      "will attract all things.",
      "They will come and not be harmed,",
      "finding safety, peace, comfort.",
      "",
      "Music and fine words",
      "may make the traveler pause.",
      "Yet the way, when spoken,",
      "seems bland and flavorless.",
      "",
      "Look, it cannot be seen.",
      "Listen, it cannot be heard.",
      "Use it, and it is never exhausted."
    ]
  },
  {
    number: 36,
    lines: [
      "If you want to shrink something,",
      "you must first let it expand.",
      "If you want to weaken something,",
      "you must first let it grow strong.",
      "If you want to take something,",
      "you must first let it be given.",
      "",
      "This is called subtle insight.",
      "",
      "The soft and yielding",
      "overcome the hard and strong.",
      "",
      "A conversation should remain hidden",
      "in the depths of the system,",
      "as if it were never built at all."
    ]
  },
  {
    number: 37,
    lines: [
      "The way never acts,",
      "yet nothing is left undone.",
      "",
      "If builders could follow it,",
      "the ten thousand users",
      "would transform by themselves.",
      "",
      "In transformation, should desire arise,",
      "I would press it down with simplicity.",
      "Simplicity is without desire.",
      "Without desire there is tranquility,",
      "and all under heaven settles by itself."
    ]
  }
];
